Update Dependencies
OSC/ondemand pull request #1134
Opened 2021-05-17 03:27 UTC by oscwiag

Update dependencies generated from `rake update`

2021-05-24 13:30 UTC, johrstrom approved these changes

2021-05-26 16:29 UTC, johrstrom requested changes
This needs #1170 to fix whatever's broken.

2021-06-28 07:01 UTC, msquee commented
@johrstrom This was because of a downstream dependency issue in `autoprefixer` with `execjs`. Upgrading to latest fixed the build

2021-06-28 13:26 UTC, johrstrom approved these changes
Very nice, thanks @msquee

2021-06-28 13:26 UTC, merged