bugfix
OSC/ondemand pull request #1345
Opened 2021-08-17 01:58 UTC by ayushchatur

### Implementation details: 

1. As referred from [archived active jobs](https://github.com/OSC/ood-activejobs/blob/master/app/views/jobs/_job_details_node_view.html.erb) plugin the semantic of the changes were in bad shape. There were incomplete ``` HTML <tr> <td> blocks in [ _job_details_node_view](apps/dashboard/app/views/active_jobs/_job_details_node_view.html.erb).
Hence this was rectified along with:
2. An additional table that was used but not required to render the ganglia graphs in [_ganglia_graphs_table](apps/dashboard/app/views/active_jobs/_ganglia_graphs_table.html.erb)

2021-08-17 14:32 UTC, johrstrom requested changes
Your commits don't seem to be associated with your GH user. Is it the right `user.email` git config?

2021-08-20 15:10 UTC, ayushchatur commented
@johrstrom rebased with correct author

2021-08-23 17:10 UTC, johrstrom commented
You still have the unknown user in the commit history.

2021-08-23 18:29 UTC, ayushchatur commented
raised another #1360

2021-08-23 18:29 UTC, closed without merging