Added functionality to view yaml files inline with browser
OSC/ondemand pull request #1758
Opened 2022-01-07 04:10 UTC by gbyrketosc

2022-01-07 14:25 UTC, johrstrom commented on apps/dashboard/app/models/files.rb
> +    castToTextArray = ['text/*','application/x-yml','application/x-yaml','application/yml','application/yaml']
ruby variables are `snake_case`.

2022-01-07 14:38 UTC, johrstrom commented on apps/dashboard/app/models/files.rb
> +    type
For multi-line blocks you want to you want to use the `do end` type notation. 

```ruby
foo.each do |ele|
  # the block
end
```
But I got a one liner for ya

```suggestion
    type = 'text/plain; charset=utf-8' if plain_cast_array.any? { |mime| /#{mime}/.match?(type) }

    type
```

I'll have to check the rubocop `Style/RegexpLiteral` - but looking at it now I think I do prefer slashes.

2022-01-07 14:45 UTC, gbyrketosc commented on apps/dashboard/app/models/files.rb
> +    castToTextArray = ['text/*','application/x-yml','application/x-yaml','application/yml','application/yaml']
changed.

2022-01-07 16:06 UTC, johrstrom requested changes
code itself seems fine, but you have some linting errors.

2022-01-10 15:14 UTC, johrstrom approved these changes

2022-01-10 15:14 UTC, merged