Adding icon picker and display, scroll bar missing border still and i…
OSC/ondemand pull request #2019
Opened 2022-05-12 21:06 UTC by Oglopf

…con not updating when selected still

2022-05-16 20:52 UTC, Oglopf commented on apps/dashboard/app/models/project.rb
> +      Project.new( name: full_path.basename )
This currently breaks at the update as there is only a `name` to be served back to populate fields.

2022-05-25 14:50 UTC, Oglopf commented on apps/dashboard/app/models/project.rb
> +  include ActiveModel::Validations::Callbacks
This was from a previous strategy that was backed out and now this needs removed.

2022-05-26 16:35 UTC, gbsoftwaresolutions requested changes
The only thing that I found was user experience issue.

If there is an "Error" during initial create/edit of project, the name and description revert to previous value (empty on create, latest saved values on edit)

2022-05-26 19:55 UTC, Oglopf commented on apps/dashboard/app/models/project.rb
> +  validates :icon, format: {
Yeah, good catch!

2022-05-26 21:49 UTC, Oglopf commented
> The only thing that I found was user experience issue.
> 
> If there is an "Error" during initial create/edit of project, the name and description revert to previous value (empty on create, latest saved values on edit)

Good catch. Got the parameters passing back now, but I need to clean up a bit and write a few tests to catch this too.

2022-05-27 18:35 UTC, Oglopf commented on apps/dashboard/app/controllers/projects_controller.rb
> +    params[:name].nil? || params[:name].empty? ? @project = Project.new : @project = Project.new({ name: params[:name], icon: params[:icon] })
Still adjusting this to be more robust.

2022-06-30 19:42 UTC, gerald-byrket approved these changes

2022-06-30 19:48 UTC, merged