add an initializer to cleanup old bc output directories
OSC/ondemand pull request #2482
Opened 2023-01-12 17:29 UTC by johrstrom

Fixes #2363 by providing 2 new configs.

The first, `bc_clean_old_dirs` turns this feature on at all. The system will then clean all output directories that had been created before `bc_clean_old_dirs_days` ago (defaults to 30 days ago).

2023-01-12 17:30 UTC, johrstrom commented on apps/dashboard/config/initializers/upgrade_to_2.1.rb
> +Rails.application.config.after_initialize do
This isn't really a part of this PR, but I just figured this is a better stage to do this work.

2023-01-13 04:01 UTC, gerald-byrket approved these changes
Ran several tests with different ages for directory.  used 30, 0, -1

each did as I expected.

2023-01-13 14:39 UTC, johrstrom commented
> Ran several tests with different ages for directory. used 30, 0, -1

Thanks. It seems like it shouldn't work for negative numbers. Let me cast to default if it's 0 or negative.  It should be at least 1 day in the past so you don't delete something that's currently running.

2023-01-13 17:36 UTC, gerald-byrket requested changes
Fix error mentioned and this will be good.

2023-01-13 17:36 UTC, gerald-byrket commented on apps/dashboard/config/initializers/bc_cleanup.rb
> +  config_days = 30 if config_days.zero? || config.days.negative?
```suggestion
  config_days = 30 if config_days.zero? || config_days.negative?
```

2023-01-13 18:43 UTC, gerald-byrket approved these changes

2023-01-18 15:34 UTC, merged